[tool.poetry]
name = "fastapi-monorepo-test"
version = "0.1.0"
description = ""
authors = ["이준환 <joonhwan.lee@mirero.co.kr>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
